# Neofetch for Faraw VER 1 REV 2
print("              &#BGGGPPPPPPPGGBB&          user@faraw")
print("          &&  BGGBB##&&&&&##BBG#  ##&     ----------")
print("       &BGPB                      BPPG#&  OS: Faraw")
print("     &BPPB&         &&&&&           #GPG  Host: FR0381")
print("    BPPB&      &BGGPPPGGG#  #B#&          Kernel: python3")
print("  &GPG&     &BPPGB#&&&      #GGPGB&       Packages: 3")
print(" &GPB     &GPPB&               &BPPB&     Shell: FarawMain")
print(" GPG     &GPB      &&#BB##&      &GPG#    DE: None")
print("&GG&      &&     #GPPGGGGGPPB&     #PP#   Theme: Default")
print("        BG&     BPP#&     &BPP#     BPP&  Terminal: gnome-terminal")
print("BG#    &PP#     BB&         &#&      GPB  ")
print("PPB    &PPB                   ##      &   ")
print("GPG     BPG                  #PP&    &B#")
print("&PP#    &GPG&               &GPB     GPG")
print(" BPP&    &BPP#             #GPB     #PP#")
print("  BPP#     #GPPB#     &&#BGPG#     #PP# ")
print("    &GPG            &&&&       &#GPG&   ")
print("      && &B#&                #GPPG#     ")
print("         &GGPGGB##&&&&&##B#  #B#&       ")
print("            &#BGGPPPPPPPGGB             ")
print("Presiona ENTER para cerrar...")
input()